- name: "[RKE] - Create workspace directory: {{ output_dir|default('~') }}/data"
  file:
    path: "{{ output_dir|default('~') }}/data"
    state: directory
    recurse: True

- name: "[RKE] - SSH-Keys exchanges."
  include_tasks: ssh-exchanges.yml
  vars:
    hostname: "{{ node.address|trim|ansible.netcommon.ipaddr }}"
    username: "{{ cluster.user }}"
    password: "{{ cluster.password }}"
  with_items:
    - "{{ cluster.nodes|default([]) }}"
  loop_control:
    loop_var: node

- name: "[RKE] - Install pre-requisites on the nodes."
  include_tasks: nodes-prerequisites.yml
  args:
    apply:
      delegate_to: "{{ node.address|trim|ansible.netcommon.ipaddr }}"
      delegate_facts: true
  with_items:
    - "{{ cluster.nodes|default([]) }}"
  loop_control:
    loop_var: node

- name: "[RKE] - Generate the cluster.yml file."
  template:
    src: templates/cluster.yml.j2
    dest: "{{ lookup('env', 'HOME') }}/data/cluster.yml"
    force: True

- debug:
    msg:
      - "STARTING THE {{ devops_command|upper }} TASK..."
  tags: [print_action]

- name: "[RKE] UP/REMOVE"
  shell: "{{ 'rke up' if devops_command|default('')|trim != 'remove' else 'rke remove --force' }}"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/data"
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/data/kube_config_cluster.yml"
    RKE_CONFIG: "{{ lookup('env', 'HOME') }}/data/cluster.yml"
  register: reg_rke_task

- debug:
    msg:
      - "↓↓ RESULTING BASE64 ENCODED KUBECONFIG ↓↓"
      - "{{ lookup('file', lookup('env', 'HOME') + '/data/kube_config_cluster.yml', rstrip=False) | b64encode }}"
      - "↑↑ RESULTING BASE64 ENCODED KUBECONFIG ↑↑"
  tags: [print_action]
  when: devops_command|default('')|trim != 'remove'

- debug:
    msg: "{{ reg_rke_task.stdout }}"
  tags: [print_action]
  when: devops_command|default('')|trim == 'remove'